language: node_js
node_js:
  - 20.3.0
dist: focal
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script: 
  - nohup npm run server &
  - sleep 3
  - npm run test